version: '2'
services:
    testservice:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - DJANGO_SETTINGS_MODULE=chapp.settings
        env_file:
            - .env
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - '8000:8000'
        container_name: testservice
