# Generated by Django 4.0.2 on 2022-02-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0003_room_type_remove_room_max_guests_remove_room_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='state',
            field=models.CharField(choices=[('NEW', 'Freshman'), ('DEL', 'Sophomore')], default='NEW', max_length=3),
        ),
        migrations.AlterField(
            model_name='book',
            name='code',
            field=models.CharField(default='Y2I2F05H', max_length=8),
        ),
    ]
