# Generated by Django 4.0.2 on 2022-02-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0004_book_state_alter_book_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='code',
            field=models.CharField(default='K54RFLPA', max_length=8),
        ),
        migrations.AlterField(
            model_name='book',
            name='state',
            field=models.CharField(choices=[('NEW', 'Nueva'), ('DEL', 'Eliminada')], default='NEW', max_length=3),
        ),
    ]
