# Generated by Django 4.0.2 on 2022-02-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0005_alter_book_code_alter_book_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='code',
            field=models.CharField(default='17X2TBQ9', max_length=8),
        ),
        migrations.AlterField(
            model_name='book',
            name='state',
            field=models.CharField(choices=[('NEW', 'Nueva'), ('DEL', 'Cancelada')], default='NEW', max_length=3),
        ),
    ]
