# Generated by Django 4.0.2 on 2022-02-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0006_alter_book_code_alter_book_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='checkin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='checkout',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='code',
            field=models.CharField(default='FY21EQS9', max_length=8),
        ),
    ]
