# Generated by Django 4.0.2 on 2022-02-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0008_alter_book_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='checkin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='checkout',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='code',
            field=models.CharField(default='TFHBZMWZ', max_length=8),
        ),
    ]
