# Generated by Django 4.0.2 on 2022-02-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0009_alter_book_checkin_alter_book_checkout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='checkin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='checkout',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='code',
            field=models.CharField(default='NGE6LJ15', max_length=8),
        ),
    ]
