# Generated by Django 4.0.2 on 2022-02-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0012_booking_delete_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='code',
            field=models.CharField(default='JO82BVQ2', max_length=8),
        ),
    ]
