# Generated by Django 4.0.2 on 2022-02-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0013_alter_booking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='code',
            field=models.CharField(max_length=8),
        ),
    ]
